stages:
  - build

build:
  stage: build
  only:
    - master
  tags:
    - mozmeao
    - aws
  script:
    - docker-compose build
    - docker-compose run test
    - docker-compose down
    - docker-compose push web
