stages:
  - build
  - deploy

include:
  - remote: "https://raw.githubusercontent.com/mozmeao/gitlab-library/e008d3eb69070c2214a2b25d26565af16fbb7b45/helm.yml"

build:
  stage: build
  only:
    - master
  tags:
    - mozmeao
    - aws
  script:
    - make test
    - make push
  after_script:
    - make stop

deploy-stage:
  stage: deploy
  only:
    - master
  tags:
    - mozmeao
    - aws
  extends:
    - .helm_deploy_aws
  variables:
    subdir: "k8s"
    KUBECONFIGS: "oregon-b:/home/gitlab-runner/.kube/oregon-b.kubeconfig"
    NS: www-firefox-com-stage
  when: on_success
