stages:
  - build
  - deploy
  - test

include:
  - remote: "https://raw.githubusercontent.com/mozmeao/gitlab-library/v1.0.0/job_imports.yml"

build:
  stage: build
  only:
    - master
    - prod
  extends:
    - .aws_runner
  script:
    - bin/build-and-push.sh
    - make test
  after_script:
    - make stop

.deploy:
  stage: deploy
  extends:
    - .aws_runner
    - .helm_deploy_aws
  variables:
    subdir: "k8s"
    KUBECONFIGS: "oregon-b:/home/gitlab-runner/.kube/oregon-b.kubeconfig"
  when: on_success

.test:
  stage: test
  extends:
    - .aws_runner
  variables:
    KUBECONFIG: "/home/gitlab-runner/.kube/oregon-b.kubeconfig"
  script:
    - make wait-for-deploy
    - make test-external

deploy-stage:
  extends:
    - .deploy
  only:
    - master
  variables:
    NS: www-firefox-com-stage

deploy-prod:
  extends:
    - .deploy
  only:
    - prod
  variables:
    NS: www-firefox-com-prod

test-stage:
  extends:
    - .test
  only:
    - master
  variables:
    NS: www-firefox-com-stage
    BASE_URL: http://a45dd64a3955f11eabf5f06855448c47-2111790911.us-west-2.elb.amazonaws.com:443

test-prod:
  extends:
    - .test
  only:
    - prod
  variables:
    NS: www-firefox-com-prod
    BASE_URL: http://ab2648d199aa111eabf5f06855448c47-1106149848.us-west-2.elb.amazonaws.com:443
