stages:
  - build
  - deploy

include:
  - remote: "https://raw.githubusercontent.com/mozmeao/gitlab-library/b4544c03c1e415450e426b2fa0c2eeb0d4476b38/helm.yml"

build:
  stage: build
  only:
    - master
  tags:
    - mozmeao
    - aws
  script:
    - make test
    - make push
  after_script:
    - make stop

deploy-stage:
  stage: deploy
  only:
    - master
  tags:
    - mozmeao
    - aws
  extends:
    - .helm_deploy_aws
  variables:
    subdir: "k8s"
    KUBECONFIGS: "oregon-b:/home/gitlab-runner/.kube/oregon-b.kubeconfig"
    NS: www-firefox-com-stage
  before_script:
    - export VERSION="$CI_COMMIT_SHORT_SHA"
