stages:
  - build
  - deploy
  - test

include:
  - remote: "https://raw.githubusercontent.com/mozmeao/gitlab-library/v1.1.0/job_imports.yml"

build:
  stage: build
  extends:
    - .aws_runner
  only:
    - master
    - prod
  script:
    - bin/build-and-push.sh
    - make test
  after_script:
    - make stop

.deploy:
  stage: deploy
  extends:
    - .aws_runner
    - .helm_deploy_aws
  variables:
    subdir: "k8s"
    KUBECONFIGS: "oregon-b:/home/gitlab-runner/.kube/oregon-b.kubeconfig"
  when: on_success

.test:
  stage: test
  extends:
    - .aws_runner
  variables:
    KUBECONFIG: "/home/gitlab-runner/.kube/oregon-b.kubeconfig"
  script:
    - make wait-for-deploy
    - make test-external

deploy-stage:
  extends:
    - .deploy
  variables:
    ENV: stage
    NS: www-firefox-com-stage

deploy-prod:
  extends:
    - .deploy
  only:
    - prod
  variables:
    ENV: prod
    NS: www-firefox-com-prod

test-stage:
  extends:
    - .test
  only:
    - master
  variables:
    NS: www-firefox-com-stage
    BASE_URL: https://fxc-stage.oregon-b.moz.works

test-prod:
  extends:
    - .test
  only:
    - prod
  variables:
    NS: www-firefox-com-prod
    BASE_URL: http://fxc-prod.oregon-b.moz.works
