version: '3.4'
services:
  web:
    image: mozmeao/www.firefox.com:${CI_COMMIT_SHORT_SHA:-latest}
    build:
      context: .
    ports:
    - 8080:8080
    volumes:
    - ./content/:/app/content:delegated

  test:
    image: mozmeao/www.firefox.com:tests-${CI_COMMIT_SHORT_SHA:-latest}
    build:
      context: tests
    depends_on:
      - web
    environment:
      BASE_URL: http://web:8080

  test-external:
    image: mozmeao/www.firefox.com:tests-${CI_COMMIT_SHORT_SHA:-latest}
    environment:
      BASE_URL: https://www.firefox.com
