version: '3.4'
services:
  web:
    image: mozmeao/www.firefox.com:${CI_COMMIT_SHORT_SHA:-latest}
    build:
      context: .
    ports:
    - 8080:80

  test:
    image: mozmeao/www.firefox.com:tests-${CI_COMMIT_SHORT_SHA:-latest}
    build:
      context: tests
    depends_on:
      - web
    environment:
      BASE_URL: http://web
