apiVersion: v1
kind: Service
metadata:
  name: www-firefox-com
  labels:
    run: www-firefox-com
  annotations:
     service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
     service.beta.kubernetes.io/aws-load-balancer-ssl-cert: ${SSLARN}
     external-dns.alpha.kubernetes.io/hostname: ${DNSADDR}
spec:
  type: LoadBalancer
  ports:
  - port: 443
    targetPort: 8080
    protocol: TCP
  selector:
    app: www-firefox-com
